#!/bin/sh

# needs
# yum openldap-clients
# apt ldap-utils                                                                       
# zypper openldap2-client

export PATH=/usr/sbin:/sbin:/usr/bin:/bin

# checks to see if /etc/krb5.keytab has nfs service
#   if not print "needkey". Otherwise prints nothing

HOSTNAME=`hostname`
if klist -k -t /etc/krb5.keytab | grep "/$HOSTNAME@" > /dev/null 2>&1
then
exit 0
else
# wrong host, remove bad keys and ipa configuration. otherwise ipa-client-install failss                                                                                      
rm -rf /etc/krb5.keytab /etc/ssh/ssh_host*
echo changed
fi

# make sure we have ssh keys                                                           
if sshd-keygen
then
  :
elif ssh-keygen -A
then 
  :
else
  /etc/init.d/sshd restart
fi
